language: go

go:
  - 1.13.x

go_import_path: github.com/lynic/network-attachment-definition-client
install: true
script: 
  - hack/verify-codegen.sh
  - go test ./pkg/...
  - go build ./cmd/example/
